version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node_app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis
    

volumes:
  mongo-db: